# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on any branch or tag commit
  push:
    branches:
      - "*"
    tags:
      - "v*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Este trabajo maneja el despliegue
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install Python packages
        run: pip install -r requirements.txt
        
      - name: Creates pipeline
        env:
          SF_ACCOUNT_2: ${{ secrets.SF_ACCOUNT_2 }}
          SF_USER_2: ${{ secrets.SF_USER_2 }}
          SF_PWD_2: ${{ secrets.SF_PWD_2 }}
          SF_ROLE_2: ${{ secrets.SF_ROLE_2 }}
          SF_WAREHOUSE_2: ${{ secrets.SF_WAREHOUSE_2 }}
          SF_DATABASE_2: ${{ secrets.SF_DATABASE_2 }}
          SF_SCHEMA_2: ${{ secrets.SF_SCHEMA_2 }}
        run:
          python $GITHUB_WORKSPACE/feature_store_and_model_registry.py
